name: Sanity checks

on: [push, pull_request]

jobs:
  sanity_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: |
          sudo apt-get -y install build-essential python3-pip ninja-build
          pip install meson
      - name: Sanity Checks
        run: |
          git fetch --unshallow --tags
          ./tools/sanity_checks.py
